### ISSUE TITLE
三栏布局

### ISSUE THREAD

**Issue by JuneJH** [JuneJH/blog#19]
# 三栏布局

> 固定两列，中间那列自适应

## 1. flex

> 弹性盒子极大的简化了布局难点
> 目前兼容性尚可
> [关于flex](https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex)

1. 代码示例

```html

    <div class="container">
      <div class="left">左边</div>
      <div class="main">中间</div>
      <div class="right">右边</div>
    </div>
    <p style="background-color: red; margin: 0">测试高度塌陷</p>

```

```css

    html,
    body {
      /* 清除浏览器默认margin */
      margin: 0;
    }
    /* 使用弹性盒子布局方式 */
    .container{
      display: flex;
    }
    /* 固定左栏宽度 */
    .left{
      width: 200px;
      background-color: aquamarine;
    }
    /* 中间自适应宽度 */
    .main{
      flex:1;
      background-color: #008c8c;
    }
    /* 固定右栏宽度 */
    .right{
      width: 200px;
      background-color: aquamarine;
    }

```

**在浏览器渲染时，会按照dom树结构次序进行渲染，我们肯定更想优先渲染主体部分即中间的内容，只需要修改dom结构就可以满足浏览器规则**
## 2. 圣杯布局

> 结构上 中(main)左(left)右(right)
> 最外层通过`padding`为左右栏留出位置
> 利用浮动改变子元素显示的次序
> 浮动将导致外层容器(内容撑高)缺失高度
> 利用margin让其分布到两侧
> 利用相对定位使其归位至padding留出的位置
> 当浏览器宽度无限变小时，该方案会乱版
> 采用给予父级最小宽度

代码示例

```html

  <div class="container">
    <div class="main">中间</div>
    <div class="left">左边</div>
    <div class="right">右边</div>
  </div>
  <p style="background-color: red;margin: 0;">测试高度塌陷</p>

```

```css
 html,body{
    /* 清除浏览器默认margin */
    margin: 0;
  }
  .container{
    /* 利用padding留出固定两栏的位置,假设左右固定为200px */
    padding: 0 200px;
    /* 设置最小宽度,避免乱版  */
    /* min-width: 500px; */
  }
  /* 清除浮动，避免后续内容受到影响 */
  .container::after{
    content: "";
    display: block;
    clear: both;
  }
  /* 全体浮动，触发BFC */
  .main,.left,.right{
    float: left;
  }
  /* 设置左右共同样式，固定宽度，为了好观察设置背景颜色 */
  .left,.right{
    width: 200px;
    background-color: rgb(163, 245, 30);
  }
  /* 设置主区域，主区域宽度跟随浏览器自适应 */
  .main{
    width: 100%;
    background-color: aqua;
  }
  .left{
    /* 通过margin-left让左边区域到相对左边一点，并回到同一行 */
    margin-left: -100%;
    /* 利用position定位，让左边区域到外层所留的padding中 */
    position: relative;
    left:-200px;
  }
  /* 同理  */
  .right{
    margin-left:-200px;
    position: relative;
    right:-200px;
  }

```

**圣杯布局在浏览器宽度无限小的时候会产生左右栏掉出中间栏行，双飞翼布局在改变一定的dom结构解决该问题**

## 3. 双飞翼布局

> 结构上 中(main(实际框为content))左(left)右(right)
> 同理，通过浮动修改dom显示次序
> 左右依旧固定宽度，通过`margin`回到最左/最右位置
> 中间增加一层包裹层(此时`mian`为包裹层)，与左右栏同一层级，获得`100%`的宽度
> 实际中间显示层为`content`，并且从左栏宽度处开始，到减去右栏宽度处，通过`margin`处理

1. 代码示例

```html

 <div class="container">
    <div class="main">
      <div class="content">中间</div>
    </div>
    <div class="left">左边</div>
    <div class="right">右边</div>
  </div>
  <p style="background-color: red;margin: 0;">测试高度塌陷</p>

```

```css
   html,body{
    /* 清除浏览器默认margin */
    margin: 0;
  }
  /* 清除浮动 */
  .container::after{
    content: "";
    display: block;
    clear: both;
  }
  /* 整体浮动 */
  .main,.left,.right{
    float: left;
  }
  /* 初始化左右 */
  .left,.right{
    width: 200px;
    background-color: aquamarine;
  }
  /* 主体占据所有的宽度，它只是包裹层，实际展示为其子元素 */
  .main{
    width: 100%;
  }
  /* 真实中间 */
  .content{
    margin: 0 200px;
    background-color: #008c8c;
  }
  /* 把左栏归位 */
  .left{
    margin-left: -100%;
  }
  /* 右栏归位 */
  .right{
    margin-left: -200px;
  }
```

### 4. 绝对定位

> 该方案在已知高度的情况下可行(解决包裹层的高度问题)
> 外层为布局父级可以通过`position:relative`实现
> 相应栏通过`position:absolute`去到它应该在的位置

1. 代码示例

```html

    <div class="container">
      <div class="main">中间</div>
      <div class="left">左边</div>
      <div class="right">右边</div>
    </div>
    <p style="background-color: red; margin: 0">测试高度塌陷</p>

```

```css

    html,
    body {
      /* 清除浏览器默认margin */
      margin: 0;
    }
    /* 父级参考，已知高度 */
    .container {
      position: relative;
      height: 200px;
    }
    /* 初始化 */
    .left,
    .main,
    .right {
      position: absolute;
    }
    /* 去到左栏 */
    .left {
      left: 0;
      width: 200px;
      background-color: aquamarine;
    }
    /* 宽度由position展开，自适应 */
    .main {
      left: 200px;
      right: 200px;
      background-color: #008c8c;
    }
    /* 去到右栏 */
    .right {
      right: 0;
      width: 200px;
      background-color: aquamarine;
    }

```

## 布局

- 根据不同的需求选择合适的布局方式,需求才是和最佳实践挂钩的
- 一通则百通,两栏布局，一栏布局。。。
